# Generated by Django 5.2.1 on 2025-06-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multishopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=100)),
                ('ownerName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('businessType', models.CharField(max_length=100)),
                ('taxId', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
