# Generated by Django 5.2.1 on 2025-06-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multishopapp', '0002_modelregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comparePrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('option', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('priceAdjustment', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dimensions', models.CharField(max_length=100, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
