# Generated by Django 5.2.1 on 2025-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multishopapp', '0003_products_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='product/'),
        ),
    ]
