# Generated by Django 5.2.1 on 2025-06-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multishopapp', '0005_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('create_account', models.BooleanField(default=False)),
                ('ship_to_different', models.BooleanField(default=False)),
                ('shipping_first_name', models.CharField(blank=True, max_length=100)),
                ('shipping_last_name', models.CharField(blank=True, max_length=100)),
                ('shipping_email', models.EmailField(blank=True, max_length=254)),
                ('shipping_mobile', models.CharField(blank=True, max_length=20)),
                ('shipping_address1', models.CharField(blank=True, max_length=255)),
                ('shipping_address2', models.CharField(blank=True, max_length=255)),
                ('shipping_country', models.CharField(blank=True, max_length=100)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100)),
                ('shipping_zip_code', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
    ]
